[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/.netlify/functions/image"
  to = "/api/image"
  status = 200
  force = true
